server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  mongodb:
    embedded:
      version: 4.0.2
    data:
      mongodb:
        database: catalog
        port: 27017
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/parcialback
#    username: root
#    password: ProyectoFinal
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true

info:
  application:
    name: api-catalog

eureka:
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j.retry:
  instances:
    retryCatalog:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.net.ConnectException

resilience4j.circuitbreaker:
  instances:
    clientCatalog:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10